### ISSUE TITLE
Where Is setup.py?

### ISSUE THREAD

**Issue by ellabebop** [HumphreysCarter/BUFKIT-BUFR-Data-Parser#2]
The install instructions in _README.md_ refer to a _setup.py_ file, but there isn't one in the repo.  Just guessing, I came up with this.

```python
import setuptools

setuptools.setup(
   name="bufkit-api",
   version="1.1",
   description="Provides a Python interface to BUFKIT BUFR files.",
   url="https://github.com/HumphreysCarter/bufkit-api",
   author="Carter Humphreys",
   packages=setuptools.find_packages(include=["bufkit*"])
)
```

**Comment by HumphreysCarter** [comment]
Hi, yeah I hadn't gotten around to creating that file just yet. If that worked for you, feel free to create a pull request and I'll merge it.

**Comment by ellabebop** [comment]
PR submitted.  Thanks for the reply and for providing this extension.

**Comment by HumphreysCarter** [comment]
Thanks for the PR! 😁
